changelog:
  categories:
    - title: Emergency Hot-fixes 🚅
      labels:
        - "hotfix"
        - "semver-patch"
      exclude:
        authors:
          - dependabot
          - dependabot[bot]

    - title: Breaking Changes 🚅
      labels:
        - "semver-major"
        - "breaking-change"

    - title: Exciting New Features 🚀
      labels:
        - "story"
        - "feature"
        - "semver-minor"
      exclude:
        labels:
          - dependencies

    - title: 🐛 Bug Fixes
      labels:
        - "bug"
        - "bugfix"
        - "semver-patch"

    - title: 🧪 Research
      labels:
        - "research"
        - "semver-patch"

    - title: ⬆️ Dependencies
      labels:
        - "dependencies"
        - "semver-patch"

    - title: 🛠️ Maintenance
      labels:
        - "maintenance"
        - "chore"
        - "*"
        - "semver-patch"
