changelog:
  categories:
    - title: General Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: DevOps Changes
      labels:
        - devops
      exclude:
        labels:
          - dependencies
    - title: Dependency Changes
      labels:
        - dependencies