changelog:
  categories:
    - title: General Changes
      labels:
        - '*'
      exclude:
        authors:
          - dependabot
    - title: DevOps Changes
      labels:
        - devops
      exclude:
        authors:
          - dependabot
    - title: Dependencies
      authors:
        - dependabot
