version: '3.8'
services:
  app:
    # M1 Compatibility
    # platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-production}
    ports:
      - '3000:3000'
