version: "3.8"
services:
  app:
    env_file:
      # Provide environment variables for local Docker use.
      # During deployments, Docker Compose and .env* files are not used.
      # Instead, environment variables are sourced from KeyVaults and sent as
      # build args to the Dockerfile.
      - .env
      - .env.production
    build:
      context: .
    ports:
      - "3000:3000"
