module.exports = {
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  jsxSingleQuote: true,
  importOrder: [
    '<BUILTIN_MODULES>',
    '^react$',
    '^react-router-dom$',
    '^react-(.*)$',
    '<THIRD_PARTY_MODULES>',
    '^@mui/material(.*)$',
    '^@mui/icons-material(.*)$',
    '^(.*)mocks/(.*)$',
    '^(.*)api/(.*)$',
    '^(.*)pages/(.*)$',
    '^(.*)types/(.*)$',
    '^(.*)context/(.*)$',
    '^(.*)utilities/(.*)$',
    '^(.*)components/Icons/(.*)$',
    '^(.*)components/(.*)$',
    '^(.*)components/commons/(.*)$',
    '^src/(.*)$',
    '^./public/(.*)$',
    '^(?!.*\\.module\\.scss)./(.*)$',
    '^../(.*)$',
    '^./(.*)module.scss$',
  ],
};
