name: Use node_modules cache

description: Uses node_modules and caches the result

inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: '16'

runs:
  using: 'composite'
  steps:
    # Installs node and caches the global yarn cache (does not cache node_modules)
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    # Caches node_modules, breaks cache when yarn.lock is updated
    - name: Cache dependencies
      id: dependency-cache
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
          /home/runner/.cache/Cypress
        key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

    # Installs dependencies from the cached packages in the global yarn cache if the cache was broken
    - name: Install dependencies
      if: steps.dependency-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
