name: Use build cache

description: Builds the Next.js app and caches the result

inputs:
  build-args:
    description: 'ENV vars for build step'
    required: false

runs:
  using: 'composite'
  steps:
    # Caches the app's build files, breaks cache when yarn.lock is updated or when a .js/.jsx file is updated
    - name: Cache build
      id: build-cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}

    # Builds the app if the cache was broken
    - name: Build app
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: ${{ inputs.build-args }} yarn build
      shell: bash
