name: 🚀 Development AKS Deploy

on:
  push:
    branches: [development]
    paths-ignore:
      - "**/*.md"
      - "**/*.ps1"
      - "**/Secrets.json*"
      - ".*ignore"
      - ".devcontainer/"
      - ".vscode/"
      - ".github/"
      - "!.github/workflows/aks-development.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  # Cancel an in-progress deploy if a newer one is pending

jobs:
  deploy:
    name: Execute AKS Deployment
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/aks-deploy.yaml@2
    with:
      environment: development
      environmentKeyVault: ${{ vars.AZURE_KEYVAULT_PREFIX }}-development
      chartsPath: ./deployments/development-charts
      maximumReplicas: 4
      ingressWhitelist: '207.67.20.252'
    secrets:
      azureClusterName: ${{ secrets.AKS_CLUSTER_NAME }}
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      registryHostName: ${{ secrets.TODO_IMAGE_NAME_HOSTNAME }}
      registryUserName: ${{ secrets.TODO_IMAGE_NAME_USERNAME }}
      registryPassword: ${{ secrets.TODO_IMAGE_NAME_PASSWORD }}
      storageAccountKey: ${{ secrets.TODO_CLOUD_KEY }}
