name: 'Production AKS Deploy'

on:
  release:
    types: [released, deleted]

jobs:
  deploy:
    name: Execute AKS Deployment
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/aks-deploy.yaml@2.1.16
    with:
      repositoryName: ${{ github.event.repository.name }}
      environment: production
      environmentKeyVault: appname-production
      clusterName: amuaks201
      clusterResourceGroup: AMU_AKS_201
      aksIngressFqdn: amuaks201-production-ingress.centralus.cloudapp.azure.com.
      dnsResourceGroup: AMU_DNS_RG
      chartsPath: ./deployments/charts/
      dockerFilePath: .
      dockerImageName: ${{ github.event.repository.name }}
      dockerImageTag: ${{ github.sha }}
      maximumReplicas: 30
      storageAccountName: amucloudapps
      appInfoTableName: DeployedApplications
      environmentIngress: false
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      registryUserName: ${{ secrets.AMUAPPIMAGES201_USERNAME }}
      registryPassword: ${{ secrets.AMUAPPIMAGES201_PASSWORD }}
      storageAccountKey: ${{ secrets.AMUCLOUDAPPS_KEY }}

  update_boley_dns:
    needs: deploy
    name: Update Boley DNS
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/update-addns.yaml@2.1.16
    with:
      environment: production
      repositoryName: ${{ github.event.repository.name }}
      storageAccountName: amucloudapps
      appInfoTableName: DeployedApplications
    secrets:
      domainController: ${{ secrets.BOLEY_DC }}
      storageAccountKey: ${{ secrets.AMUCLOUDAPPS_KEY }}
