name: Development AKS Deploy

on:
  push:
    branches: [development]
    paths-ignore:
      - "**/*.md"
      - "**/*.ps1"
      - "**/Secrets.json*"
      - ".*ignore"
      - ".devcontainer/"
      - ".vscode/"
      - ".github/"
      - "!.github/workflows/aks-development.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Do not cancel in-progress deploys, allow one pending run of the most recent changes

jobs:
  deploy:
    name: Execute AKS Deployment
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/aks-deploy.yaml@2
    with:
      environment: development
      environmentKeyVault: ${{ vars.AZURE_KEYVAULT_PREFIX }}-development
      chartsPath: ./deployments/charts/development-charts
      maximumReplicas: 4
      ingressWhitelist: '207.67.20.252'
    secrets:
      azureClusterName: ${{ secrets.AKS_CLUSTER_NAME }}
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      registryHostName: ${{ secrets.AMUAPPIMAGES201_HOSTNAME }}
      registryUserName: ${{ secrets.AMUAPPIMAGES201_USERNAME }}
      registryPassword: ${{ secrets.AMUAPPIMAGES201_PASSWORD }}
      storageAccountKey: ${{ secrets.AMUCLOUDAPPS_KEY }}
