name: Application CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      # Filter out Dependabot PRs
      - '!dependabot/**'
    paths-ignore:
      - '**/*.md'
      - '**/*.ps1'
      - '**/Secrets.json*'
      - '.*ignore'
      - '.github/'
      - '!.github/workflows/application-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  statuses: write

env:
  environment: development

jobs:
  # Sets up dependencies and initial cache
  setup-and-build:
    name: Setup and Build Application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/use-build-args-cache
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/use-node-modules-cache

      - uses: ./.github/actions/use-build-cache

  # Reformats code
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: [setup-and-build]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_ACTION_CI }}

      - uses: ./.github/actions/use-build-args-cache

      - uses: ./.github/actions/use-node-modules-cache

      - uses: ./.github/actions/use-build-cache

      - name: Lint javascript
        run: yarn lint:js

      - name: Lint scss
        run: yarn lint:styles

      # This step must be after other jobs or steps that might add or change files
      - name: Format all
        run: yarn format-all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: amutechtest
          commit_user_email: amu_deploy@amuniversal.com
          commit_message: Apply prettier changes

  # Run Jest Unit tests
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [lint-and-format]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/use-build-args-cache

      - uses: ./.github/actions/use-node-modules-cache

      - uses: ./.github/actions/use-build-cache

      - name: Run Jest tests
        run: yarn test:unit:ci

  # Runs Playwright integration tests
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    # needs: [build, check-linters]
    needs: [lint-and-format]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/use-build-args-cache

      - uses: ./.github/actions/use-node-modules-cache

      - uses: ./.github/actions/use-build-cache

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:integration:ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

  check-links:
    name: Check Application Links
    runs-on: ubuntu-latest
    needs: [lint-and-format]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/use-build-args-cache

      - uses: ./.github/actions/use-node-modules-cache

      - uses: ./.github/actions/use-build-cache

      - name: Run Broken Link Checker
        id: link-checker-report
        continue-on-error: true
        run: yarn postbuild && yarn test:links

      - name: Link Checker Results
        if: ${{ failure() }}
        run: echo "::warning ${{steps.link-checker-report.outputs.result}}"

  # Checks gzipped page sizes, uses caches from setup-and-build
  check-size:
    runs-on: ubuntu-latest
    name: Get File Sizes Limits
    needs: [lint-and-format]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/use-build-args-cache

      - uses: ./.github/actions/use-node-modules-cache

      - uses: ./.github/actions/use-build-cache

      - name: Run Size Limit Report
        id: link-checker-report
        continue-on-error: true
        run: yarn test:size

  required-checks:
    name: Required Checks
    runs-on: ubuntu-latest
    needs: [integration-tests,unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
