name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      test-command:
        description: "Test command to run"
        required: true
        type: string
      artifact-name:
        description: "Base artifact name"
        required: true
        type: string
      timeout-minutes:
        description: "Job timeout in minutes"
        required: false
        type: number
        default: 30
      upload-path:
        description: "Path to upload as artifacts"
        required: false
        type: string
        default: ""

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js App
        uses: ./.github/actions/setup-ui
      - name: Run Tests and Check Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: ${{ inputs.test-command }}
          package-manager: npm
          annotations: failed-tests

      # - name: Run tests
      #   run: ${{ inputs.test-command }}
      - name: Upload test artifacts
        if: ${{ inputs.upload-path != '' && always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.upload-path }}
          retention-days: 7
