name: ⬆️ Bump Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: Type of release
        options:
          - major
          - minor
          - patch

jobs:
  bump-versions:
    name: Bump Versions
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/bump-versions.yaml@2
    with:
      releaseType: ${{ inputs.releaseType }}
    secrets:
      PAT_ACTION_CI: ${{ secrets.PAT_ACTION_CI }}

  required-checks:
    name: Required Checks
    runs-on: ubuntu-latest
    needs: [bump-versions]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
