name: 🚀 AKS Deployment

on:
  push:
    branches: [main]
  release:
    types: [released, prereleased]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vars:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Get Environment Variables
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Retrieve Environment Variables
        run: |
          if [ ${{ github.ref == 'refs/heads/main' }} == true ]; then
              # Development Environment
              echo "environment=development" >> $GITHUB_ENV
              echo "maximumReplicas=2" >> $GITHUB_ENV
              echo "ingressWhitelist=207.67.20.252" >> $GITHUB_ENV
          elif [[ ${{ github.event_name == 'release' && github.event.release.prerelease }} == true ]]; then
              # Staging Environment
              echo "environment=staging" >> $GITHUB_ENV
              echo "maximumReplicas=4" >> $GITHUB_ENV
              echo "webAuthentication=true" >> $GITHUB_ENV
              echo "ingressWhitelist=207.67.20.252" >> $GITHUB_ENV
          elif [[ ${{ github.event_name == 'release' && !github.event.release.prerelease }} == true ]]; then
              # Production Environment
              echo "environment=production" >> $GITHUB_ENV
              echo "environmentIngress=false" >> $GITHUB_ENV
          fi
    outputs:
      environment: ${{ env.environment }}
      maximumReplicas: ${{ env.maximumReplicas }}
      environmentIngress: ${{ env.environmentIngress }}
      ingressWhitelist: ${{ env.ingressWhitelist }}
      webAuthentication: ${{ env.webAuthentication }}

  deploy:
    needs: [vars]
    name: Execute AKS Deployment
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/aks-deploy.yaml@2
    with:
      environment: ${{ needs.vars.outputs.environment }}
      environmentKeyVault: ${{ vars.AZURE_KEYVAULT_PREFIX }}-${{ needs.vars.outputs.environment }}
      webAuthentication: ${{ needs.vars.outputs.webAuthentication || 'false' }}
      chartsPath: ./deployments/${{ needs.vars.outputs.environment }}-charts
      environmentIngress: ${{ needs.vars.outputs.environmentIngress || 'true' }}
      maximumReplicas: ${{ needs.vars.outputs.maximumReplicas || '30' }}
      ingressWhitelist: ${{ needs.vars.outputs.ingressWhitelist || '207.67.20.252' }}
    secrets:
      azureClusterName: ${{ secrets.AKS_CLUSTER_NAME }}
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      registryHostName: ${{ secrets.IMAGE_NAME_HOSTNAME }}
      registryUserName: ${{ secrets.IMAGE_NAME_USERNAME }}
      registryPassword: ${{ secrets.IMAGE_NAME_PASSWORD }}
      storageAccountKey: ${{ secrets.STORAGE_KEY }}
      webAuthenticationPassword: ${{ secrets.WEB_AUTHENTICATION_PASSWORD }}
      webAuthenticationUsername: ${{ secrets.WEB_AUTHENTICATION_USERNAME }}
