name: Run Jira Linter

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      fail-on-error:
        type: string
        description: A Boolean which, if set to true, fails the GitHub Action when an error occurs. Default true.
        default: ${{ vars.JIRA_LINT_FAIL_ON_ERROR || 'false' }}
      skip-comments:
        type: string
        description: A Boolean if set to true then action-jira-linter will skip adding lint comments for PR title.
        default: ${{ vars.JIRA_LINT_SKIP_COMMENTS || 'true' }}
    secrets:
      JIRA_TOKEN:
        required: true

env:
  githubPrBranch: ${{ github.head_ref }}
  githubPrTitle: ${{ github.event.pull_request.title }}

jobs:
  jira-lint:
    name: Run Jira Lint
    if: ${{ github.actor != 'dependabot[bot]' && !contains(github.head_ref, 'sync') && !contains(github.event.pull_request.labels.*.name, 'disable-jira-linter') }}
    runs-on: ubuntu-latest
    steps:
      - uses: jira-tools/action-jira-linter@v1.0.1
        name: Jira Lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://${{ env.JIRA_DOMAIN }}.atlassian.net
          pr-threshold: 1000
          jira-user: ${{ env.JIRA_USER }}
          validate-issue-status: false
          skip-branches: "^(main|development|develop|dev|test|testing|staging|qa|master|production)$"
          fail-on-error: false
          skip-comments: false
