name: Lighthouse Performance Audit
on: [pull_request]
jobs:
  performance_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Performance Budget of PR
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: '.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Commit Lighthouse Report
        if: success() || failure()
        run: |
          git config user.name "Lighthouse Bot"
          git config user.email "actions@github.com"
          git add .lighthouseci/
          git commit -m "chore(ci): update Lighthouse report [skip ci]" || echo "No changes to commit"
          git push || echo "Push failed (likely due to PR context)"

