name: Lighthouse CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        continue-on-error: true
        with:
          urls: |
            https://admin.wayroo-dev-beta.com/
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Check Lighthouse Budgets
        run: |
          SUMMARY_FILE="$GITHUB_STEP_SUMMARY"
          echo "## Lighthouse Budget Failures" >> "$SUMMARY_FILE"
          FAIL=0
          for f in .lighthouseci/lhr-*.json; do
            if jq -e '.audits["resource-summary"].details.items[] | select(.overBudget)' "$f" > /dev/null; then
              URL=$(jq -r '.finalUrl' "$f")
              echo "- **$URL** exceeded resource budgets!" >> "$SUMMARY_FILE"
              FAIL=1
            fi
          done
          if [ $FAIL -eq 0 ]; then
            echo "All budgets passed. 🎉" >> "$SUMMARY_FILE"
          fi
        shell: bash
