name: Next.js Application CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build App
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Lint javascript
        run: npm run lint:js
      - name: Lint scss
        run: npm run lint:styles

      - name: Setup Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push Linting Fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_message: "[CI] Applying formatting and linting changes"

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run Jest tests
        run: npm run test:unit:ci


  integration-tests:
    name: Integration Tests
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Run Playwright tests (GitHub Action)
        uses: microsoft/playwright-github-action@v1
        with:
          upload-artifact: true
          html-report: true

