name: Add PR Labels

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PAT_ACTION_CI:
        required: true

jobs:
  # Automatically apply labels that match globs, defined in .github/labeler.yml
  # https://github.com/marketplace/actions/labeler
  triage-labels:
    name: Apply labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.PAT_ACTION_CI }}
          sync-labels: true
