name: CI Pull Request (Bypass)

# This action is used to bypass required status checks when files are changed that do not impact the app or require testing

on:
  pull_request:
    branches:
      - 'development'
      - 'main'
    paths:
      # Match the paths-ignore in pull-request.yml
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Required status check
  lint-code:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Status Checks
      - name: Update commit status
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.PAT_ACTION_CI }}
          status: '${{ job.status }}'

  # Required status check
  test-in-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Status Checks
      - name: Update commit status
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.PAT_ACTION_CI }}
          status: '${{ job.status }}'
