name: 📄 Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
