name: Storybook Deployment

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-storybook:
    name: Deploy to Storybook
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Environment variables
        run: |
          if [[ "${{ github.ref }}" != 'refs/heads/main' ]] && [[ "${{ github.ref }}" != 'refs/tags/**' ]]; then
            echo "environment=development" >> $GITHUB_ENV
          elif [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]] && [[ "${{ contains(github.ref,'-rc') }}" == "true" ]]; then
            echo "environment=staging" >> $GITHUB_ENV
          elif [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true"  ]]; then
            echo "environment=production" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Install Cache Action
        uses: ./.github/actions/use-install-cache

      - name: Publish to Storybook
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
          exitZeroOnChanges: ${{ env.environment == 'development' }}
          allowConsoleErrors: false
          onlyChanged: true
          skip: ${{ env.environment == 'development' }}
          autoAcceptChanges: ${{ env.environment == 'production' }}
