name: 📝 Storybook Deployment

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Storybook
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pozetroninc/github-action-get-latest-release@v0.7.0
        id: latest_release
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
          token: ${{ secrets.PAT_ACTION_CI }}

      - name: Use cache-yarn-install action
        uses: Andrews-McMeel-Universal/cache-yarn-install@v1

      - name: Publish to Storybook
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
          exitZeroOnChanges: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
          allowConsoleErrors: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
          onlyChanged: true
          skip: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
          autoAcceptChanges: ${{ contains(github.ref, steps.latest_release.outputs.release) }}
