name: 🔄 Sync with template-nextjs-ui

on:
  schedule:
    - cron: 0 9 1 JAN,APR,JUL,OCT *
  workflow_dispatch:
    inputs:
      isdryrun:
        type: boolean
        description: Dry run
        default: false

jobs:
  repo-sync:
    name: Repository Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch or tag
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_ACTION_CI }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.1
        with:
          github_token: ${{ secrets.PAT_ACTION_CI }}
          source_repo_path: ${{ (vars.USER_NAME || github.repository_owner) }}/template-nextjs-ui
          upstream_branch: main
          pr_labels: sync
          pr_commit_msg: 🔄 Synchronize with ${{ (vars.USER_NAME || github.repository_owner) }}/template-nextjs-ui
          pr_title: 🔄 Sync with @${{ (vars.USER_NAME || github.repository_owner) }}/template-nextjs-ui
          pr_branch_name_prefix: sync/template-nextjs-ui/
          # pr_reviewers: ${{ (vars.USER_NAME || github.repository_owner) }}
          is_dry_run: ${{ inputs.isdryrun || 'false' }}
          # git_user_name: ${{ (vars.USER_NAME || github.repository_owner) }}
          # git_user_email: ${{ vars.USER_EMAIL || '' }}
